# These are supported funding model platforms

github: [yutiansut]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: pypi/quantaxis
custom: http://pic.yutiansut.com/alipay.png
