language: python
python:
  - "3.5.2"
 
os: "ubuntu"
# whitelist

  
install:
- sudo apt-get update
- git clone https://github.com/yutiansut/quantaxis
- cd quantaxis
- git checkout 0.3.9-gamma


before_script:
# command to install dependencies
- pip install -r requirements.txt
 
# command to build
script: 
- python setup.py install
 
#after_success:
    #"python easy_start_tushare.py"


  