version: '2'
services:
    qa:
        image: yutiansut/qa-jupyter:latest
        container_name: qajupyter
        networks: 
            qanetwork:
                ipv4_address: 172.19.0.3
        ports:
            - "8888:8888"
        environment:
          - MONGODB=172.19.0.2
        volumes:
            - qacode:/home
        restart: always

    # qacron:
    #     image: barretthugh/qa-cron
    #     environment:
    #         - MONGODB=mgdb
    #     restart: always

    qaweb:
        image: yutiansut/qarun
        container_name: qarun
        networks: 
            qanetwork:
                ipv4_address: 172.19.0.4
        ports:
            - "8010:8010"
        environment:
          - MONGODB=172.19.0.2
        restart: always
        depends_on:
          - rabbit

    mgdb:
        image: mongo:4.1.3
        ports:
            - "27017:27017"
        environment:
            - TZ=Asia/Shanghai
            - MONGO_INITDB_DATABASE=quantaxis
        volumes:
            - qamg:/data/db
        networks: 
            qanetwork:
                ipv4_address: 172.19.0.2
        restart: always


    rabbit:
        image: rabbitmq:management
        ports: 
            - "15672:15672"
            - "5672:5672"
            - "4369:4369"
        networks: 
            qanetwork:
                ipv4_address: 172.19.0.5
        restart: always
volumes:
    qamg:
        external:
            name: qamg
    qacode:
        external:
            name: qacode
networks:
    qanetwork:
        ipam:
            config:
            - subnet: 172.19.0.0/24
              gateway: 172.19.0.1