{% set data = load_setup_py_data() %}
package:
  name: quantaxis
  version: {{ data.get('version') }}

source:
  git_url: ../

build:
  entry_points:
    - quantaxis=QUANTAXIS.QACmd:QA_cmd
    - quantaxisq=QUANTAXIS.QAFetch.QATdx_adv:bat
    - qarun=QUANTAXIS.QACmd.runner:run

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - pytz
    - six
    - nbformat >=4.4.0
    - clyent >=1.2.0
    - requests >=2.9.1
    - PyYAML >=3.12
    - python-dateutil >=2.6.1
    - pymongo
    - bs4
    - pandas
    - lxml
    - matplotlib
    - requests
    - numpy>=1.12.0
    - pytesseract
    - gevent-websocket>=0.10.1
    - apscheduler>=3.3.1
    - tornado
    - zenlog
    - pyecharts
    - protobuf>=3.4
    - motor>=1.1
    - retrying
    - seaborn>=0.8.1
    - selenium
    - scrapy
    - attrs>=17.4.0
    - pyconvert>=0.6.3
    - demjson>=2.2.4


about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: MIT
  license_file: LICENSE
  summary: {{ data.get('description') }}